### ISSUE TITLE
apollo client resetStore triggers an error related to the defaults from apollo-link-state

### ISSUE THREAD

**Issue by wowzaaa** [apollographql/apollo-link-state#194]
Hi everyone,

I lost 2 day on this issue and i decided to ask for you help because i will loose my mind with this :)

My technology stack is the following one:
Server: AWS Lambda, Apollo Server, AWS Api Gateway, AWS RDS MySQL
Client: Apollo Client, Apollo Link State, Apollo Cache Persist

This is my defaults object:
```javascript
export const defaults = {
    access: {
        shouldCheckTokens: false,
        isSignedIn: false,
        __typename: 'AccessState'
    }
};
```

So what i need to do is implement authentication in a serverless environment ... so i am storing 2 jwt tokens on the client that are generated upon login

What i was trying to do to top everything up is that if the client reloads the page to keep him logged in but to recheck the tokens and if they are not ok to actually resetStore

so this is the code that is supposed to do that:
```javascript
let storeDefaults = defaults;
const cache = new InMemoryCache();

persistCache({
    cache,
    storage: window.localStorage,
    trigger: 'write',
}).then(() => {
    try {
        decode(localStorage.getItem(WOWZAAA_TOKEN));
        decode(localStorage.getItem(WOWZAAA_REFRRSH_TOKEN));
        storeDefaults.access.shouldCheckTokens = true;
        storeDefaults.access.isSignedIn = true;
    } catch (e) {}
    
    const stateLink = withClientState({
        resolvers,
        cache,        
        defaults: storeDefaults,
    });
    const httpLink = createHttpLink({
        uri: 'https://api.wowzaaa.io/graphql'
    });
    const authLink = setContext((_, context) => {
        const { headers } = context;
        const token = localStorage.getItem(WOWZAAA_TOKEN);
        const refreshToken = localStorage.getItem(WOWZAAA_REFRRSH_TOKEN);
        return {
            headers: {
                ...headers,
                'wwz-token': token ? token : null,
                'wwz-refresh-token': refreshToken ? refreshToken : null
            }
        }
    })

    const client = new ApolloClient({
        cache,
        link: ApolloLink.from([stateLink, authLink.concat(httpLink)])
    });
    client.onResetStore(stateLink.writeDefaults);

    if (!document.getElementById('main-app')) {
        let div = document.createElement('div');
        div.id = "main-app";
        document.body.appendChild(div);
    }
    ReactDOM.render(
        <ApolloProvider client={client}>
            <Router>
                <Main />
            </Router>
        </ApolloProvider>,
        document.getElementById('main-app')
    );
});
```

so on resetStore i now get this:
```
ApolloError.js:34 Uncaught (in promise) Error: Network error: Cannot read property 'access' of undefined
    at new ApolloError (ApolloError.js:34)
    at QueryManager.js:218
    at <anonymous>
```
```
react-apollo.browser.umd.js:545 Unhandled (in react-apollo:Apollo(Apollo(Apollo(Apollo(withHandlers(lifecycle(pure(Main)))))))) Error: Network error: Cannot read property 'access' of undefined
    at new ApolloError (http://localhost:8080/vendor.84f481ea0da53644f8c9.js:41113:28)
    at ObservableQuery.u1/p.ObservableQuery.currentResult (http://localhost:8080/vendor.84f481ea0da53644f8c9.js:41224:24)
    at GraphQL.dataForChild (http://localhost:8080/vendor.84f481ea0da53644f8c9.js:7212:62)
    at GraphQL.render (http://localhost:8080/vendor.84f481ea0da53644f8c9.js:7262:33)
    at finishClassComponent (http://localhost:8080/vendor.84f481ea0da53644f8c9.js:53664:31)
    at updateClassComponent (http://localhost:8080/vendor.84f481ea0da53644f8c9.js:53641:12)
    at beginWork (http://localhost:8080/vendor.84f481ea0da53644f8c9.js:54016:16)
    at performUnitOfWork (http://localhost:8080/vendor.84f481ea0da53644f8c9.js:56015:16)
    at workLoop (http://localhost:8080/vendor.84f481ea0da53644f8c9.js:56079:26)
    at HTMLUnknownElement.callCallback (http://localhost:8080/vendor.84f481ea0da53644f8c9.js:46333:14)
```

so if anyone can help me not loose my mind i would really appreciate it :)

thanks

**Comment by akiran** [comment]
This could be related to this issue https://github.com/apollographql/apollo-link-state/issues/187

**Comment by wowzaaa** [comment]
yes ... i guess no fix for now :(

**Comment by akiran** [comment]
@wowzaaa  Can you try this PR by installing locally https://github.com/apollographql/apollo-link-state/pull/193 . This is still experimental PR. But want to know if it fixes you issue

**Comment by wowzaaa** [comment]
well this is embarrassing :D but can you tell me how i can i do that exactly :D?

**Comment by peggyrayzis** [comment]
#187 is now fixed! Upgrading to the latest versions of `apollo-cache-inmemory` and `apollo-link-state` should now fix your issue. Thank you for your patience 😀

**Comment by wowzaaa** [comment]
i am sry to say that i still have the error :)

packake.json
```javascript
"dependencies": {
    "animate.css": "^3.5.2",
    "apollo-cache-inmemory": "^1.1.7",
    "apollo-cache-persist": "^0.1.1",
    "apollo-client": "^2.2.2",
    "apollo-link-context": "^1.0.3",
    "apollo-link-http": "^1.3.2",
    "apollo-link-state": "^0.4.0",
    "autoprefixer": "^7.2.5",
    "aws-sdk": "^2.188.0",
    "axios": "^0.17.1",
    "babel-polyfill": "^6.26.0",
    "babel-runtime": "^6.26.0",
    "bootstrap": "^4.0.0",
    "compression-webpack-plugin": "^1.1.6",
    "css-loader": "^0.28.9",
    "dotenv": "^4.0.0",
    "graphql-tag": "^2.6.1",
    "jwt-decode": "^2.2.0",
    "react": "^16.2.0",
    "react-apollo": "^2.0.4",
    "react-async-script": "^0.9.1",
    "react-dom": "^16.2.0",
    "react-google-recaptcha": "^0.9.9",
    "react-router": "^4.2.0",
    "react-router-dom": "^4.2.2",
    "script-ext-html-webpack-plugin": "^1.8.8",
    "style-loader": "^0.19.1",
    "uglify": "^0.1.5",
    "webfontloader": "^1.6.28",
    "yup": "^0.24.0"
  }
```

**Comment by wowzaaa** [comment]
`"apollo-utilities": "^1.0.6",`

same errors as in the initial post

**Comment by akiran** [comment]
@wowzaaa you have to update apollo-cache-inmemory to 1.1.7 and apollo-link-state to 0.4.0

**Comment by wowzaaa** [comment]
u can see they have the latest version in package.json ... i deleted node_modules ... reinstalled ... nothing :(

**Comment by wowzaaa** [comment]
@peggyrayzis  please reopen this

here is a reproduction of the error:
[https://codesandbox.io/s/v69v13w0o0](https://codesandbox.io/s/v69v13w0o0)

**Comment by akiran** [comment]
Yes, this issue still exists. 

```client.onResetStore(stateLink.writeDefaults);``` as mentioned in the docs didn't resolve this issue.
I think, after resetStore is called, counter query is executed before onResetStore callback execution. 

If onResetStore callback is executed before counter query, this problem might be solved

**Comment by akiran** [comment]
@wowzaaa you can temporarily fix the crashing of your app by add {} as fallback to resolverMap at [line](https://github.com/apollographql/apollo-link-state/blob/master/packages/apollo-link-state/src/index.ts#L75)

change line 75 to 
```var resolverMap = resolvers[rootValue.__typename || type] || {};```

check Local Development section of readme, if want to know how to make changes locally and test it

**Comment by wowzaaa** [comment]
nope :( same thing

btw do i need to do anything special to reopen this issue? or maybe repost it
